### PR TITLE
Fixed Issue #10 : slow_ajax_load

### PR DESCRIPTION
**Pull request by rb2k**
Fixed Issue #10 : slow_ajax_load by replacing non existant local jquery link to a CDN one

### CODE REVIEW

**Comment by rb2k** [comment]
Not 100% sure how to use a local jquery file, but as far as I remember, some other tests need network connection too

```
Capybara::Session
  with akephalos driver
    slow page load
      should wait for the page to finish loading
    slow ajax load
      should wait for ajax to load

Finished in 7.35 seconds
3 examples, 0 failures
```

**Comment by Nerian** [comment]
Thank you a lot!

We are getting close to have a totally green test suite :)

Merging

**Comment by Nerian** [comment]
@rb2k

Ooops, I closed in the same instant that you post a new message :)

You can put a jQuery file in spec/support/

**Comment by Nerian** [comment]
@rb2k:

I tried to put a jquery file there, but I get:

```
Errno::ENOENT - No such file or directory - /Users/Nerian/.rvm/gems/ruby-1.9.3-rc1@akephalos2/gems/capybara-1.1.1/lib/capybara/spec/views/jquery.js.erb:
```

The Test application is running from the Capybara side. We could use an absolute path to reach out our support folder, but I think that won't pay much. jQuery is only going to be downloaded once, just for that spec so I think is right as it is :)

**Comment by rb2k** [comment]
Yeah, I tried it with File.read() and other things too, but since other tests use the internet connectivity too, it doesn't seem to hurt.

**Pull request merged**
